// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sRc35IzxQh2P6N8W_P5Lr-gWoniyqe4',
    appId: '1:1066676033089:android:1cae801e785bd0b45b98c0',
    messagingSenderId: '1066676033089',
    projectId: 'pg-mart-ac9fe',
    storageBucket: 'pg-mart-ac9fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtQOCRBo7jqZv4dccEx4AZQ8qjdDHVmDw',
    appId: '1:1066676033089:ios:b6852c4f7a728c9c5b98c0',
    messagingSenderId: '1066676033089',
    projectId: 'pg-mart-ac9fe',
    storageBucket: 'pg-mart-ac9fe.firebasestorage.app',
    iosBundleId: 'com.example.pgMart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH1BAamBxKLRBHvtoS5AoCN3oqOvtT1h0',
    appId: '1:1066676033089:web:26d8242dcbd578d65b98c0',
    messagingSenderId: '1066676033089',
    projectId: 'pg-mart-ac9fe',
    authDomain: 'pg-mart-ac9fe.firebaseapp.com',
    storageBucket: 'pg-mart-ac9fe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH1BAamBxKLRBHvtoS5AoCN3oqOvtT1h0',
    appId: '1:1066676033089:web:5788d45e10ef0cd45b98c0',
    messagingSenderId: '1066676033089',
    projectId: 'pg-mart-ac9fe',
    authDomain: 'pg-mart-ac9fe.firebaseapp.com',
    storageBucket: 'pg-mart-ac9fe.firebasestorage.app',
  );

}